name: carryon
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.4.4 <4.0.0"

dependencies:
    cloud_firestore: ^5.2.0
    firebase_auth: ^5.1.3
    firebase_core: ^3.3.0
    flutter:
        sdk: flutter
    shared_preferences: ^2.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true

    # Enable generation of localized Strings from arb files.
    generate: true

    assets:
        # Add assets from the images directory to the application.
        - assets/images/
